version: '2.0'

services: 
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hVFczfhPh3
      MYSQL_USER: local
      MYSQL_PASSWORD: HB8eUewdjn
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql 